services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
      - ./config_backup:/tmp
      - ./backup:/backup
    environment:
      - TZ=Asia/Bangkok
      - INFLUXD_LOG_LEVEL=info
      - TMPDIR=/var/lib/influxdb2
    command: influxd
 
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    depends_on:
      - influxdb
    env_file:
      - ./env_file/.env
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - TZ=Asia/Bangkok

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    restart: always
    depends_on:
      - influxdb
    env_file:
      - ./env_file/.env
    environment:
      - TZ=Asia/Bangkok
      - GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD  #change the password
    links:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./plugins:/var/lib/grafana/plugins      
  

