[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  debug = true # เปิดไว้ดู Log ว่าได้รับข้อมูลจาก MQTT หรือยัง

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
	token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"

[[inputs.mqtt_consumer]]
  servers = ["$MQTT_SERVER"]
  ## แก้ไขตรงนี้ให้ครอบคลุมทุก Sub-topic ##
  topics = [
		"$MQTT_TOPICS_1",
  #  "$MQTT_TOPICS_2", 
  #  "$MQTT_TOPICS_3", 
  ]
  username = "$MQTT_USER"
  password = "$MQTT_PASSWORD"
  data_format = "json"
	tag_keys = ["ip", "mac", "status"]
	
	# tag_keys = ["type"]
	# json_time_key = "timestamp"
  # json_time_format = "unix"

# # --- ชุดใหม่สำหรับเก็บค่า STATUS (ตัวหนังสือ) ---
# [[inputs.mqtt_consumer]]
#   servers = ["tcp://mqtt.encare.ai:1883"]
#   topics = [
#     "MEGA-IOT-0001/STATUS",
# #    "ESP32-IOT-0001/STATUS"
#   ]
#   username = "mqttclient"
#   password = "%139User"

#   # ใช้ format แบบ value เพื่อดึงค่าออกมาตรงๆ
#   data_format = "value"
#   data_type = "string" # กำหนดว่าเป็นตัวหนังสือ

#   # กำหนดชื่อ Field ใน InfluxDB ว่าจะให้ชื่ออะไร
#   name_override = "device_status"

# # เพิ่มตรงนี้เพื่อดูผ่าน Log ว่า Telegraf อ่าน JSON ออกมาเป็นหน้าตาอย่างไร
# [[outputs.file]]
#   files = ["stdout"]